spring:
  security:
    oauth2:
      client:
        registration:
          categories-client-oidc:
            provider: spring
            client-id: oidc-client
            client-secret: oidc-secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/{registrationId}"
            scope: openid
            client-name: categories-client-oidc
          categories-client-authorization-code:
            provider: spring
            client-id: oidc-client
            client-secret: oidc-secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/authorized"
            scope: categories.read
            client-name: categories-client-authorization-code
        provider:
          spring:
            issuer-uri: https://auth.josdem.io/